//USER
// on login
export const USER_LOG_IN_REQUESTED = 'USER_LOG_IN_REQUESTED';
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
export const USER_LOG_IN_FAILURE = 'USER_LOG_IN_FAILURE';
// on logout
export const USER_LOG_OUT_REQUESTED = 'USER_LOG_OUT_REQUESTED';
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
export const USER_LOG_OUT_FAILURE = 'USER_LOG_OUT_FAILURE';
// on User created
export const USER_CREATION_REQUESTED = 'USER_CREATION_REQUESTED';
export const USER_CREATION_SUCCESS = 'USER_CREATION_SUCCESS';
export const USER_CREATION_FAILTURE = 'USER_CREATION_FAILTURE';

//CURRENTS
export const CURRENT_NOTEBOOK_SETTED = 'CURRENT_NOTEBOOK_SETTED';
export const CURRENT_NOTE_SETTED = 'CURRENT_NOTE_SETTED';

//NOTAS
//Fetch ALL notes
export const FETCH_NOTES_REQUESTED = 'FETCH_NOTES_REQUESTED';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';
//Fetch ONE note
export const FETCH_NOTE_REQUESTED = 'FETCH_NOTE_REQUESTED';
export const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
export const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE';
//Add one note
export const ADD_NOTE_REQUESTED = 'ADD_NOTE_REQUESTED';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAILURE = 'ADD_NOTE_FAILURE';
//Remove one note
export const REMOVE_NOTE_REQUESTED = 'REMOVE_NOTE_REQUESTED';
export const REMOVE_NOTE_SUCCESS = 'REMOVE_NOTE_SUCCESS';
export const REMOVE_NOTE_FAILURE = 'REMOVE_NOTE_FAILURE';
//Share one note
export const SHARE_NOTE_REQUESTED = 'SHARE_NOTE_REQUESTED';
export const SHARE_NOTE_SUCCESS = 'SHARE_NOTE_SUCCESS';
export const SHARE_NOTE_FAILURE = 'SHARE_NOTE_FAILURE';
//Update a note
export const UPDATE_NOTE_REQUESTED = 'UPDATE_NOTE_REQUESTED';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAILURE = 'UPDATE_NOTE_FAILURE';


//NOTEBOOKS
//Fetch ALL NOTEBOOKs
export const FETCH_NOTEBOOKS_REQUESTED = 'FETCH_NOTEBOOKS_REQUESTED';
export const FETCH_NOTEBOOKS_SUCCESS = 'FETCH_NOTEBOOKS_SUCCESS';
export const FETCH_NOTEBOOKS_FAILURE = 'FETCH_NOTEBOOKS_FAILURE';
//Add one NOTEBOOK
export const ADD_NOTEBOOK_REQUESTED = 'ADD_NOTEBOOK_REQUESTED';
export const ADD_NOTEBOOK_SUCCESS = 'ADD_NOTEBOOK_SUCCESS';
export const ADD_NOTEBOOK_FAILURE = 'ADD_NOTEBOOK_FAILURE';
//Remove one NOTEBOOK
export const REMOVE_NOTEBOOK_REQUESTED = 'REMOVE_NOTEBOOK_REQUESTED';
export const REMOVE_NOTEBOOK_SUCCESS = 'REMOVE_NOTEBOOK_SUCCESS';
export const REMOVE_NOTEBOOK_FAILURE = 'REMOVE_NOTEBOOK_FAILURE';
//Update a NOTEBOOK
export const UPDATE_NOTEBOOK_REQUESTED = 'UPDATE_NOTEBOOK_REQUESTED';
export const UPDATE_NOTEBOOK_SUCCESS = 'UPDATE_NOTEBOOK_SUCCESS';
export const UPDATE_NOTEBOOK_FAILURE = 'UPDATE_NOTEBOOK_FAILURE';

//FRIENDOS
//add
export const ADD_FRIEND_REQUESTED = 'ADD_FRIEND_REQUESTED';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';
//remove
export const REMOVE_FRIEND_REQUESTED = 'REMOVE_FRIEND_REQUESTED';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
export const REMOVE_FRIEND_FAILURE = 'REMOVE_FRIEND_FAILURE';

//General
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_FAILED = 'USER_FAILED';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';

// SHOW CREATE NOTEBOOK
export const SHOW_NOTEBOOK_FORM = 'SHOW_NOTEBOOK_FORM';
export const HIDE_NOTEBOOK_FORM = 'HIDE_NOTEBOOK_FORM';
