//NOTAS
//Fetch ALL notes
export const FETCH_NOTES_REQUESTED = 'FETCH_NOTES_REQUESTED';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAILTURE = 'FETCH_NOTES_FAILTURE';
//Add one note
export const ADD_NOTE_REQUESTED = 'ADD_NOTE_REQUESTED';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAILTURE = 'ADD_NOTE_FAILTURE';
//Remove one note
export const REMOVE_NOTE_REQUESTED = 'REMOVE_NOTE_REQUESTED';
export const REMOVE_NOTE_SUCCESS = 'REMOVE_NOTE_SUCCESS';
export const REMOVE_NOTE_FAILTURE = 'REMOVE_NOTE_FAILTURE';
//Share one note
export const SHARE_NOTE_REQUESTED = 'SHARE_NOTE_REQUESTED';
export const SHARE_NOTE_SUCCESS = 'SHARE_NOTE_SUCCESS';
export const SHARE_NOTE_FAILTURE = 'SHARE_NOTE_FAILTURE';
//Update a note
export const UPDATE_NOTE_REQUESTED = 'UPDATE_NOTE_REQUESTED';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAILTURE = 'UPDATE_NOTE_FAILTURE';


//NOTEBOOKS
//Fetch ALL NOTEBOOKs
export const FETCH_NOTEBOOKS_REQUESTED = 'FETCH_NOTEBOOKS_REQUESTED';
export const FETCH_NOTEBOOKS_SUCCESS = 'FETCH_NOTEBOOKS_SUCCESS';
export const FETCH_NOTEBOOKS_FAILTURE = 'FETCH_NOTEBOOKS_FAILTURE';
//Add one NOTEBOOK
export const ADD_NOTEBOOK_REQUESTED = 'ADD_NOTEBOOK_REQUESTED';
export const ADD_NOTEBOOK_SUCCESS = 'ADD_NOTEBOOK_SUCCESS';
export const ADD_NOTEBOOK_FAILTURE = 'ADD_NOTEBOOK_FAILTURE';
//Remove one NOTEBOOK
export const REMOVE_NOTEBOOK_REQUESTED = 'REMOVE_NOTEBOOK_REQUESTED';
export const REMOVE_NOTEBOOK_SUCCESS = 'REMOVE_NOTEBOOK_SUCCESS';
export const REMOVE_NOTEBOOK_FAILTURE = 'REMOVE_NOTEBOOK_FAILTURE';
//Update a NOTEBOOK
export const UPDATE_NOTEBOOK_REQUESTED = 'UPDATE_NOTEBOOK_REQUESTED';
export const UPDATE_NOTEBOOK_SUCCESS = 'UPDATE_NOTEBOOK_SUCCESS';
export const UPDATE_NOTEBOOK_FAILTURE = 'UPDATE_NOTEBOOK_FAILTURE';

//FRIENDOS
//add
export const ADD_FRIEND_REQUESTED = 'ADD_FRIEND_REQUESTED';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILTURE = 'ADD_FRIEND_FAILTURE';
//remove
export const REMOVE_FRIEND_REQUESTED = 'REMOVE_FRIEND_REQUESTED';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
export const REMOVE_FRIEND_FAILTURE = 'REMOVE_FRIEND_FAILTURE';

//General
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_FAILED = 'USER_FAILED';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
