//Notes
export const ALL_NOTES_FETCH_REQUESTED = 'ALL_NOTES_FETCH_REQUESTED'
export const ALL_NOTES_FETCH_SUCCESS = 'ALL_NOTES_FETCH_SUCCESS' 
export const NOTE_ADDED = 'NOTE_ADDED';
export const NOTE_REMOVED = 'NOTE_REMOVED';
export const NOTE_SHARED = 'NOTE_SHARED';

//Notebooks
export const ALL_NOTEBOOKS_FETCH_REQUESTED = 'ALL_NOTES_FETCH_REQUESTED'
export const ALL_NOTEBOOKS_FETCH_SUCCESS = 'ALL_NOTES_FETCH_SUCCESS' 
export const NOTEBOOK_ADDED = 'NOTEBOOK_ADDED';
export const NOTEBOOK_REMOVED = 'NOTEBOOK_REMOVED';
export const NOTEBOOK_COLOR_CHANGED = 'NOTEBOOK_COLOR_CHANGED';

//Friends
export const FRIEND_ADDED = 'FRIEND_ADDED';
export const FRIEND_REMOVED = 'FRIEND_REMOVED';

//General
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const ERROR_RAISED = 'ERROR_RAISED';
export const REQUEST_SUCCEDED = 'REQUEST_SUCCEDED';
